// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type DayInfo struct {
	ID            int64        `json:"id"`
	Date          sql.NullTime `json:"date"`
	DayRange      float32      `json:"day_range"`
	WeekRange     float32      `json:"week_range"`
	MonthRange    float32      `json:"month_range"`
	YearRange     float32      `json:"year_range"`
	MarketDayDate int32        `json:"market_day_date"`
}

type Event struct {
	ID         int32     `json:"id"`
	Date       time.Time `json:"date"`
	Time       time.Time `json:"time"`
	Forecast   string    `json:"forecast"`
	Impact     string    `json:"impact"`
	LastUpdate int32     `json:"last_update"`
	Name       string    `json:"name"`
	Previous   string    `json:"previous"`
	Region     string    `json:"region"`
}

type Market struct {
	ID   int32          `json:"id"`
	Name sql.NullString `json:"name"`
}

type MarketDay struct {
	ID       int64         `json:"id"`
	Date     time.Time     `json:"date"`
	Open     float32       `json:"open"`
	High     float32       `json:"high"`
	Low      float32       `json:"low"`
	Last     float32       `json:"last"`
	Range    float32       `json:"range"`
	Volume   float32       `json:"volume"`
	Poc3yr   float32       `json:"poc3yr"`
	Poc1yr   float32       `json:"poc1yr"`
	Poc0yr   float32       `json:"poc0yr"`
	Poc1wk   float32       `json:"poc1wk"`
	Poc1m    float32       `json:"poc1m"`
	MarketID sql.NullInt32 `json:"market_id"`
}

type OpenPrice struct {
	ID        int64     `json:"id"`
	Market    string    `json:"market"`
	YearOpen  float32   `json:"year_open"`
	MonthOpen float32   `json:"month_open"`
	WeekOpen  float32   `json:"week_open"`
	Updated   time.Time `json:"updated"`
}
