// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type Event struct {
	ID         int32     `json:"id"`
	Date       time.Time `json:"date"`
	Time       time.Time `json:"time"`
	Forecast   string    `json:"forecast"`
	Impact     string    `json:"impact"`
	LastUpdate int32     `json:"last_update"`
	Name       string    `json:"name"`
	Previous   string    `json:"previous"`
	Region     string    `json:"region"`
}

type Intraday struct {
	ID        int64           `json:"id"`
	Datetime  time.Time       `json:"datetime"`
	Open      sql.NullFloat64 `json:"open"`
	High      sql.NullFloat64 `json:"high"`
	Low       sql.NullFloat64 `json:"low"`
	Close     sql.NullFloat64 `json:"close"`
	Volume    sql.NullInt32   `json:"volume"`
	Bidvolume sql.NullInt32   `json:"bidvolume"`
	Askvolume sql.NullInt32   `json:"askvolume"`
	Date      sql.NullTime    `json:"date"`
	MarketID  sql.NullInt32   `json:"market_id"`
}

type Market struct {
	ID   int32          `json:"id"`
	Name sql.NullString `json:"name"`
}

type MarketDay struct {
	ID       int64         `json:"id"`
	Date     time.Time     `json:"date"`
	Open     float32       `json:"open"`
	High     float32       `json:"high"`
	Low      float32       `json:"low"`
	Last     float32       `json:"last"`
	Range    float32       `json:"range"`
	Volume   float32       `json:"volume"`
	Poc3yr   float32       `json:"poc3yr"`
	Poc1yr   float32       `json:"poc1yr"`
	Poc0yr   float32       `json:"poc0yr"`
	Poc1wk   float32       `json:"poc1wk"`
	Poc1m    float32       `json:"poc1m"`
	MarketID sql.NullInt32 `json:"market_id"`
}
