// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type EndOfDay struct {
	ID        int64           `json:"id"`
	Date      time.Time       `json:"date"`
	Open      sql.NullFloat64 `json:"open"`
	High      sql.NullFloat64 `json:"high"`
	Low       sql.NullFloat64 `json:"low"`
	Close     sql.NullFloat64 `json:"close"`
	Volume    sql.NullInt32   `json:"volume"`
	Bidvolume sql.NullInt32   `json:"bidvolume"`
	Askvolume sql.NullInt32   `json:"askvolume"`
	MarketID  sql.NullInt32   `json:"market_id"`
}

type Event struct {
	ID         int32     `json:"id"`
	Date       time.Time `json:"date"`
	Time       time.Time `json:"time"`
	Forecast   string    `json:"forecast"`
	Impact     string    `json:"impact"`
	LastUpdate int32     `json:"last_update"`
	Name       string    `json:"name"`
	Previous   string    `json:"previous"`
	Region     string    `json:"region"`
}

type Intraday struct {
	ID        int64           `json:"id"`
	Datetime  time.Time       `json:"datetime"`
	Open      sql.NullFloat64 `json:"open"`
	High      sql.NullFloat64 `json:"high"`
	Low       sql.NullFloat64 `json:"low"`
	Close     sql.NullFloat64 `json:"close"`
	Volume    sql.NullInt32   `json:"volume"`
	Bidvolume sql.NullInt32   `json:"bidvolume"`
	Askvolume sql.NullInt32   `json:"askvolume"`
	Date      sql.NullTime    `json:"date"`
	MarketID  sql.NullInt32   `json:"market_id"`
}

type Market struct {
	ID   int32          `json:"id"`
	Name sql.NullString `json:"name"`
}
